using System.IO.Compression;
using System.Text;

// Native geometry identification only; no height or topology predicate enters runtime code.
internal static class APylonCables
{
    internal static void Emit(string directory, string previousDirectory, string destination)
    {
        MeshData Read(string suffix) => GeometryFile.Read(File.ReadAllBytes(
            Directory.GetFiles(directory, "ExtradosedBridge02PillarCablesNet" + suffix + "_*.Geometry")
                .Single(p => suffix.Length != 0 || !Path.GetFileName(p).Contains("LOD")))).Meshes.Single();
        var full = Read("");
        // The native 18 tall cable assemblies cross x=0 at their tower ends; the below-deck
        // truss and shorter roadside fixtures are not cables. Inspect their separate topology.
        var cables = Pieces.Of(full.Positions, full.Indices).Where(p => p.High > 60).ToArray();
        if (cables.Length != 18 || cables.Any(p => p.Left > 0 || p.Right < 0))
            throw new InvalidDataException("Native A-pylon cable assemblies changed.");
        var text = new StringBuilder("// <auto-generated />\nusing System;\nusing System.Collections.Generic;\nnamespace BridgeBuilder.Bridges;\ninternal static class APylonCableData\n{\n    internal static readonly IReadOnlyDictionary<string, (int Count, string Data)> Maps = new Dictionary<string, (int, string)>(StringComparer.Ordinal)\n    {\n");
        foreach (var suffix in new[] { "", "_LOD1", "_LOD2" })
        {
            var mesh = suffix.Length == 0 ? full : Read(suffix);
            var labels = Pieces.LabelsOf(mesh.Positions, mesh.Indices);
            var members = Pieces.Of(mesh.Positions, mesh.Indices).Where(p => p.High > 60).ToArray();
            // LOD2 splits each full-detail front/back pair. Match by the original cable's side
            // and tower attachment height; inherit its span, never reclassify from coarse topology.
            var reaches = members.ToDictionary(p => p.Id, p =>
            {
                var side = Math.Sign(p.Left + p.Right);
                var native = cables.Where(q => Math.Sign(q.Left + q.Right) == side)
                    .OrderBy(q => Math.Abs(q.High - p.High)).First();
                if (Math.Abs(native.High - p.High) > 0.1f)
                    throw new InvalidDataException("LOD cable does not match its native attachment.");
                return Math.Max(Math.Abs(native.Left), Math.Abs(native.Right));
            });
            var previous = GeometryFile.Read(File.ReadAllBytes(Path.Combine(previousDirectory,
                "ExtradosedBridge02 Section 17 Piece" + (suffix == "" ? "" : " " + suffix[1..]) + ".Geometry"))).Meshes.Single();
            if (previous.Positions.Length != mesh.Positions.Length || !previous.Indices.SequenceEqual(mesh.Indices))
                throw new InvalidDataException("Generated sample topology differs from native mesh.");
            using var bytes = new MemoryStream();
            using (var writer = new BinaryWriter(bytes, Encoding.UTF8, true))
                for (var i = 0; i < mesh.Positions.Length; i++)
                    if (reaches.TryGetValue(labels[i], out var reach))
                    {
                        writer.Write(i);
                        writer.Write(mesh.Positions[i].X / reach);
                    }
            var selected = Enumerable.Range(0, mesh.Positions.Length).Where(i => reaches.ContainsKey(labels[i])).ToArray();
            var attachment = selected.Where(i => Math.Abs(mesh.Positions[i].X) < 0.35f).ToArray();
            Console.WriteLine($"{suffix}: cable assemblies={members.Length}, mapped vertices={selected.Length}, "
                + $"native attachment |x|max={attachment.Max(i => Math.Abs(mesh.Positions[i].X)):R}, "
                + $"old generated |x|max={attachment.Max(i => Math.Abs(previous.Positions[i].X)):R}, "
                + $"mapped |x|max={attachment.Max(i => Math.Abs(mesh.Positions[i].X * (1 + 8.5f / reaches[labels[i]]))):R}; anchor axis x=0 unchanged.");
            using var compressed = new MemoryStream();
            using (var gzip = new GZipStream(compressed, CompressionLevel.SmallestSize, true))
                gzip.Write(bytes.ToArray());
            text.AppendLine($"        [\"ExtradosedBridge02PillarCablesNet{suffix} Mesh\"] = ({mesh.Positions.Length}, \"{Convert.ToBase64String(compressed.ToArray())}\"),");
        }
        text.AppendLine("    };\n}");
        File.WriteAllText(destination, text.ToString());
    }
}
