using System.Globalization;
using System.IO.Compression;
using System.Text;

// Offline identification only. Runtime receives exact vertex ranges, not these spatial predicates.
internal static class CoveredWoodColumns
{
    internal static void Emit(string archive, string beforeFixGeometry)
    {
        using var zip = ZipFile.OpenRead(archive);
        var names = new[]
        {
            "PedestrianBridgeCoveredWood01Cover_321693eb11cd6dbcd19faf61b9cac862.Geometry",
            "PedestrianBridgeCoveredWood01Cover_LOD1_9a6210a3c2b36fe34abf99311c03c593.Geometry",
            "PedestrianBridgeCoveredWood01Cover_LOD2_d4af66f1043b4287b5d5484901b2057b.Geometry",
        };
        var meshes = names.Select(name =>
        {
            using var stream = zip.GetEntry(name)!.Open();
            using var bytes = new MemoryStream();
            stream.CopyTo(bytes);
            return GeometryFile.Read(bytes.ToArray()).Meshes.Single();
        }).ToArray();
        var full = meshes[0];
        var parts = Pieces.Of(full.Positions, full.Indices);
        var labels = Pieces.LabelsOf(full.Positions, full.Indices);
        // These are the 17 separate rectangular uprights above the deck, not the below-deck pier.
        var columns = parts.Where(p => p.Left < 0 && p.Right > 0
            && p.Left > -0.1f && p.Right < 0.1f && p.Low > 0 && p.Low < 1 && p.High > 4
            && p.Front - p.Back < 0.4f).ToArray();
        if (columns.Length != 17) throw new InvalidDataException("CoveredWood archetype changed.");
        var ids = columns.Select(p => p.Id).ToHashSet();
        var authored = full.Positions.Where((_, i) => ids.Contains(labels[i])).ToArray();
        var left = authored.Min(p => p.X);
        var right = authored.Max(p => p.X);
        if (left != -right || authored.Any(p => p.X != left && p.X != right))
            throw new InvalidDataException("Expected constant rectangular upright faces.");

        // The user-approved width is the TOP of the real pre-fix generated column, not the
        // full widening of the road. Measure it offline; never load this sample in the game.
        var sampleBytes = File.ReadAllBytes(beforeFixGeometry);
        var sample = GeometryFile.Read(sampleBytes).Meshes.Single();
        if (sample.Positions.Length != full.Positions.Length || !sample.Indices.SequenceEqual(full.Indices))
            throw new InvalidDataException("Pre-fix sample does not match the archetype topology.");
        var top = authored.Max(p => p.Y);
        var topIndices = Enumerable.Range(0, full.Positions.Length)
            .Where(i => ids.Contains(labels[i]) && full.Positions[i].Y == top).ToArray();
        var topLeft = topIndices.Min(i => sample.Positions[i].X);
        var topRight = topIndices.Max(i => sample.Positions[i].X);
        if (!float.IsFinite(topLeft) || !float.IsFinite(topRight) || topLeft >= 0 || topRight != -topLeft)
            throw new InvalidDataException("Pre-fix column top must be centred and have positive width.");
        foreach (var column in columns)
        {
            var vertices = Enumerable.Range(0, full.Positions.Length).Where(i => labels[i] == column.Id).ToArray();
            var ends = vertices.Where(i => full.Positions[i].Y == top).ToArray();
            if (ends.Length == 0 || ends.Min(i => sample.Positions[i].X) != topLeft
                || ends.Max(i => sample.Positions[i].X) != topRight
                || vertices.Any(i => sample.Positions[i].Y != full.Positions[i].Y
                    || sample.Positions[i].Z != full.Positions[i].Z))
                throw new InvalidDataException("Pre-fix columns do not share the measured top width or placement.");
        }
        Console.Error.WriteLine($"Pre-fix top: {topLeft:R}..{topRight:R}, width {topRight - topLeft:R}; 17 columns.");

        var source = new StringBuilder("// Generated by GeometryMetaprogram --covered-wood-columns; do not hand-edit.\n"
            + "namespace BridgeBuilder.Bridges;\n\ninternal static class CoveredWoodColumnData\n{\n");
        source.AppendLine($"    internal const float HalfSpan = {right.ToString("R", CultureInfo.InvariantCulture)}f;");
        source.AppendLine("    // User-requested full-height rectangle: retain the measured pre-fix column top.");
        source.AppendLine("    // Sample SHA256: " + Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(sampleBytes)));
        source.AppendLine($"    internal const float Left = {topLeft.ToString("R", CultureInfo.InvariantCulture)}f;");
        source.AppendLine($"    internal const float Right = {topRight.ToString("R", CultureInfo.InvariantCulture)}f;");
        source.AppendLine("    internal static readonly int[][] Ranges =\n    {");
        for (var lod = 0; lod < meshes.Length; lod++)
        {
            // Every LOD inherits membership from the full-detail authored upright coordinates.
            // The shipped LOD2 deliberately has no central uprights: an empty map preserves it.
            var selected = meshes[lod].Positions.Select((p, i) => (p, i))
                .Where(v => authored.Any(p => p == v.p)).Select(v => v.i).ToArray();
            if (selected.Length != new[] { 272, 189, 0 }[lod])
                throw new InvalidDataException($"Unexpected LOD{lod} upright membership.");
            var ranges = new List<int>();
            for (var i = 0; i < selected.Length; i++)
            {
                var start = selected[i];
                while (i + 1 < selected.Length && selected[i + 1] == selected[i] + 1) i++;
                ranges.Add(start);
                ranges.Add(selected[i] + 1);
            }
            source.AppendLine("        new int[] { " + string.Join(", ", ranges) + " },");
        }
        source.AppendLine("    };\n}");
        Console.Write(source);
    }
}
