using System.Globalization;
using System.Text;

// Identification happens only offline against the native PillarTop, never in the game.
internal static class GoldenOrnament
{
    internal static void Emit(string directory, string destination)
    {
        MeshData Read(string suffix) => GeometryFile.Read(File.ReadAllBytes(
            Directory.GetFiles(directory, "SuspensionBridge03PillarTop" + suffix + "_*.Geometry")
                .Single(p => suffix.Length != 0 || !Path.GetFileName(p).Contains("LOD")))).Meshes.Single();
        var full = Read("");
        var labels = Pieces.LabelsOf(full.Positions, full.Indices);
        var pieces = Pieces.Of(full.Positions, full.Indices);
        var spoke = pieces.Single(p => p.Id == 101);
        var anchorY = spoke.High;
        // Native full-detail islands 101..109 are the central spoke and eight fan ribs.
        // The curved lower chord is welded into tower component 0. Its complete extrusion
        // has z=-2..2, y=90.73047..100.77344; do not include the column's deeper returns.
        var mask = full.Positions.Select((p, i) => labels[i] >= 101 && labels[i] <= 109
            || labels[i] == 0 && p.Y >= 90.73047f && p.Y <= 100.77344f
                && Math.Abs(p.X) <= 11.492676f && Math.Abs(p.Z) <= 2f).ToArray();
        var selected = full.Positions.Where((p, i) => mask[i]).ToArray();
        var span = selected.Max(p => p.X) - selected.Min(p => p.X);
        var text = new StringBuilder("// <auto-generated />\nusing System;\nusing System.Collections.Generic;\nnamespace BridgeBuilder.Bridges;\ninternal static class GoldenOrnamentData\n{\n");
        text.AppendLine($"    internal const float AnchorY = {anchorY.ToString("R", CultureInfo.InvariantCulture)}f;");
        text.AppendLine($"    internal const float Span = {span.ToString("R", CultureInfo.InvariantCulture)}f;");
        text.AppendLine("    internal static readonly IReadOnlyDictionary<string, (int Count, string Mask)> Maps = new Dictionary<string, (int, string)>(StringComparer.Ordinal)\n    {");
        foreach (var suffix in new[] { "", "_LOD1", "_LOD2" })
        {
            var mesh = suffix.Length == 0 ? full : Read(suffix);
            var bits = new byte[(mesh.Positions.Length + 7) / 8];
            var count = 0;
            for (var i = 0; i < mesh.Positions.Length; i++)
            {
                var closest = i;
                if (suffix.Length != 0)
                {
                    var p = mesh.Positions[i];
                    var distance = float.MaxValue;
                    for (var j = 0; j < full.Positions.Length; j++)
                    {
                        var q = full.Positions[j];
                        var d = (p.X-q.X)*(p.X-q.X)+(p.Y-q.Y)*(p.Y-q.Y)+(p.Z-q.Z)*(p.Z-q.Z);
                        if (d < distance) { distance = d; closest = j; }
                    }
                }
                if (!mask[closest]) continue;
                bits[i / 8] |= (byte)(1 << (i % 8));
                count++;
            }
            text.AppendLine($"        [\"SuspensionBridge03PillarTop{suffix} Mesh\"] = ({mesh.Positions.Length}, \"{Convert.ToBase64String(bits)}\"),");
            Console.WriteLine($"PillarTop{suffix}: ornament={count}/{mesh.Positions.Length}, anchor=(0,{anchorY:R}), span={span:R}");
        }
        text.AppendLine("    };\n}");
        File.WriteAllText(destination, text.ToString());
    }
}
