using System.IO.Compression;
using System.Text;

// Offline identification only. The longitudinal side trusses bound each complete transverse
// \\|/ assembly at x = +/-9.239746. Connector islands belong to that same assembly, not to
// independent height-slice spans. LOD vertices inherit the full-detail labels.
internal static class GoldenSupport
{
    // Measured inner surface of the authored side truss, not a centre-panel vertex cutoff.
    private const float SideInner = 9.239502f;
    // Full-detail XOY upright includes its curved gusset, not just the longitudinal wall.
    // Both End and Middle have the same measured inner-most gusset vertex.
    private const float UprightInner = 8.030762f;
    internal static void Emit(string directory, string destination)
    {
        var code = new StringBuilder("// <auto-generated />\nusing System;\nusing System.Collections.Generic;\nnamespace BridgeBuilder.Bridges;\ninternal static class GoldenSupportData\n{\n    internal static readonly IReadOnlyDictionary<string, string> Maps = new Dictionary<string, string>(StringComparer.Ordinal)\n    {\n");
        foreach (var kind in new[] { "End", "Middle" })
        {
            var stem = "SuspensionBridge03Support" + kind;
            MeshData Read(string suffix) => GeometryFile.Read(File.ReadAllBytes(
                Directory.GetFiles(directory, stem + suffix + "_*.Geometry").Single(
                    p => suffix.Length != 0 || !Path.GetFileName(p).Contains("LOD")))).Meshes.Single();
            var full = Read("");
            var pieces = Pieces.Of(full.Positions, full.Indices).ToDictionary(p => p.Id);
            var membership = Pieces.LabelsOf(full.Positions, full.Indices);
            // Include duplicated inner-face vertices used by transverse junction triangles too:
            // triangle-only membership would leave those seam copies behind and thicken the joint.
            var sideTruss = full.Positions.Select(p => Math.Abs(p.X) >= SideInner).ToArray();
            for (var i = 0; i < full.Positions.Length; i++)
            {
                var p = full.Positions[i];
                // The panel fronts are welded into component 0, but their return faces are
                // independent full-width XOY islands (End 45/50/55/...); both belong to the
                // same upright. Centre diagonal bars are separate, non-crossing islands.
                var part = pieces[membership[i]];
                var transversePanel = part.Left < 0 && part.Right > 0
                    && part.Low < -7f && part.High <= -2f && part.Front - part.Back < 1f;
                if ((membership[i] == 0 || transversePanel) && p.Y <= -2f
                    && Math.Abs(p.X) >= UprightInner)
                    sideTruss[i] = true;
            }
            var protectedSupport = new bool[full.Positions.Length];
            var spans = full.Positions.Select((p, i) =>
            {
                // The complete below-deck transverse panel is one authored assembly even where
                // rivets/plates have separate render vertices; side longitudinal trusses are rigid.
                // User-approved exception: the below-deck centre assembly retains its authored
                // coordinates. Negative membership is emitted as an identity map at every LOD.
                var piece = pieces[membership[i]];
                // The native welded support spans y=-7.5417..0.0624. A per-vertex
                // y=-2 cut split its upper chord from its lower members. Identify
                // the complete below-deck component offline, including the upper chord.
                // Middle welds railing posts (up to 1.2247 m) into component 0 as well;
                // preserve its above-deck railing behavior while including the whole truss.
                protectedSupport[i] = (piece.Id == 0 && p.Y < 0.1f)
                    || (piece.Low < -2f && piece.High < 0.1f) || p.Y <= -2f;
                if (protectedSupport[i])
                    return sideTruss[i] ? 0f : -1f;
                return piece.Left <= 0 && piece.Right >= 0
                    ? Math.Max(Math.Abs(piece.Left), Math.Abs(piece.Right)) : 0f;
            }).ToArray();
            // Diagonal thickness faces are independent eight-vertex islands in the source.
            // Their coordinates are inset from the visible XOY face; classifying that island
            // independently left it at the old width. Project onto the actual authored face
            // and carry its barycentric displacement through the extrusion instead.
            var fullCoefficients = full.Positions.Select((p, i) => spans[i] < 0 ? 0f
                : spans[i] > 0 ? p.X / spans[i] : Math.Sign(p.X)).ToArray();
            var depthFaces = new bool[full.Positions.Length];
            var faces = new Dictionary<int, List<(int A, int B, int C)>>();
            for (var t = 0; t < full.Indices.Length; t += 3)
            {
                var a = full.Indices[t]; var b = full.Indices[t + 1]; var c = full.Indices[t + 2];
                var p = full.Positions[a]; var q = full.Positions[b]; var r = full.Positions[c];
                if (p.Y > -2f || q.Y > -2f || r.Y > -2f
                    || Math.Abs(p.Z - q.Z) > 0.001f || Math.Abs(p.Z - r.Z) > 0.001f) continue;
                var key = (int)Math.Floor(p.Z);
                if (!faces.TryGetValue(key, out var list)) faces[key] = list = new();
                list.Add((a, b, c));
            }
            var mappedDepthFaces = 0;
            for (var i = 0; i < full.Positions.Length; i++)
            {
                var part = pieces[membership[i]];
                if (part.Vertices != 8 || part.High >= -2f || part.Right - part.Left < 8f
                    || part.Front - part.Back > 0.51f || part.Left <= 0 && part.Right >= 0) continue;
                var p = full.Positions[i];
                var best = double.MaxValue;
                var found = false;
                var mapped = 0f;
                for (var key = (int)Math.Floor(p.Z) - 1; key <= (int)Math.Floor(p.Z) + 1; key++)
                {
                    if (!faces.TryGetValue(key, out var list)) continue;
                    foreach (var (a, b, c) in list)
                    {
                        // Only the authored panel surface is a donor, never another thin island
                        // whose mapping may itself be awaiting reconstruction.
                        if (pieces[membership[a]].Vertices == 8) continue;
                        var u = full.Positions[a]; var v = full.Positions[b]; var w = full.Positions[c];
                        double denominator = (v.Y - w.Y) * (double)(u.X - w.X)
                            + (w.X - v.X) * (double)(u.Y - w.Y);
                        if (Math.Abs(denominator) < 1e-10) continue;
                        var alpha = ((v.Y - w.Y) * (double)(p.X - w.X)
                            + (w.X - v.X) * (double)(p.Y - w.Y)) / denominator;
                        var beta = ((w.Y - u.Y) * (double)(p.X - w.X)
                            + (u.X - w.X) * (double)(p.Y - w.Y)) / denominator;
                        var gamma = 1 - alpha - beta;
                        if (alpha < -0.001 || beta < -0.001 || gamma < -0.001) continue;
                        var depth = Math.Abs((double)p.Z - u.Z);
                        if (depth >= best) continue;
                        best = depth; found = true;
                        mapped = (float)(alpha * fullCoefficients[a] + beta * fullCoefficients[b]
                            + gamma * fullCoefficients[c]);
                    }
                }
                if (!found) throw new InvalidDataException($"Unmapped {stem} diagonal thickness vertex {i}.");
                // The outer YZ return is a vertical upright, not a sample of the
                // neighbouring diagonal's varying displacement. Barycentric projection
                // gave its lower corner 0.9347576 and its upper corner 1, shearing the
                // whole return face. Carry its complete authored side rigidly; only
                // the centre-side endpoint retains the requested identity mapping.
                fullCoefficients[i] = Math.Abs(p.X) >= UprightInner ? Math.Sign(p.X) : mapped;
                depthFaces[i] = true;
                mappedDepthFaces++;
            }
            Console.WriteLine($"{stem}: diagonal thickness vertices projected={mappedDepthFaces}");
            var buckets = new Dictionary<(int,int,int), List<int>>();
            for (var i = 0; i < full.Positions.Length; i++)
            {
                var p = full.Positions[i];
                var key = ((int)Math.Floor(p.X), (int)Math.Floor(p.Y), (int)Math.Floor(p.Z));
                if (!buckets.TryGetValue(key, out var bucket)) buckets[key] = bucket = new();
                bucket.Add(i);
            }
            foreach (var suffix in new[] { "", "_LOD1", "_LOD2" })
            {
                var mesh = suffix.Length == 0 ? full : Read(suffix);
                var coefficients = new float[mesh.Positions.Length];
                var structural = new bool[mesh.Positions.Length];
                var maxDistance = 0f;
                for (var i = 0; i < coefficients.Length; i++)
                {
                    var p = mesh.Positions[i];
                    var nearest = i;
                    if (suffix.Length != 0)
                    {
                        nearest = -1;
                        var best = float.MaxValue;
                        var bx = (int)Math.Floor(p.X); var by = (int)Math.Floor(p.Y); var bz = (int)Math.Floor(p.Z);
                        for (var x = bx-2; x <= bx+2; x++)
                        for (var y = by-2; y <= by+2; y++)
                        for (var z = bz-2; z <= bz+2; z++)
                        {
                            if (!buckets.TryGetValue((x,y,z), out var bucket)) continue;
                            foreach (var j in bucket)
                            {
                                var q = full.Positions[j];
                                var distance = (p.X-q.X)*(p.X-q.X)+(p.Y-q.Y)*(p.Y-q.Y)+(p.Z-q.Z)*(p.Z-q.Z);
                                if (distance >= best) continue;
                                best = distance; nearest = j;
                            }
                        }
                        if (nearest < 0) throw new InvalidDataException("Unmapped golden LOD vertex.");
                        maxDistance = Math.Max(maxDistance, MathF.Sqrt(best));
                    }
                    coefficients[i] = depthFaces[nearest] ? fullCoefficients[nearest]
                        : spans[nearest] < 0f ? 0f : spans[nearest] > 0f
                        ? p.X / spans[nearest] : Math.Sign(p.X);
                    structural[i] = protectedSupport[nearest];
                }
                using var bytes = new MemoryStream();
                using (var gzip = new GZipStream(bytes, CompressionLevel.SmallestSize, true))
                using (var writer = new BinaryWriter(gzip))
                    for (var i = 0; i < coefficients.Length; i++)
                    {
                        writer.Write(coefficients[i]);
                        writer.Write(structural[i]);
                    }
                code.AppendLine($"        [\"{stem}{suffix} Mesh\"] = \"{Convert.ToBase64String(bytes.ToArray())}\",");
                Console.WriteLine($"{stem}{suffix}: {coefficients.Length} vertices; mapped={coefficients.Count(c => !float.IsNaN(c))}; max LOD distance={maxDistance:R}");
                // Retain a real-archetype projection for visual inspection, not a synthetic test.
                File.WriteAllText(Path.Combine(directory, stem + suffix + "-mapped.json"),
                    System.Text.Json.JsonSerializer.Serialize(new { mesh.Positions, mesh.Indices, Labels = suffix.Length == 0 ? membership : null, Coefficients = coefficients.Select(c => float.IsNaN(c) ? (float?)null : c) }));
            }
        }
        code.AppendLine("    };\n}");
        File.WriteAllText(destination, code.ToString());
    }
}
