// Generated by GeometryMetaprogram --covered-wood-columns; do not hand-edit.
namespace BridgeBuilder.Bridges;

internal static class CoveredWoodColumnData
{
    internal const float HalfSpan = 0.08231163f;
    // User-requested full-height rectangle: retain the measured pre-fix column top.
    // Sample SHA256: 4D3C0C763AC82EA99C48B0D6EA842F2487A82376CAA1891DAD7318728AC3A0D9
    internal const float Left = -0.80877763f;
    internal const float Right = 0.80877763f;
    internal static readonly int[][] Ranges =
    {
        new int[] { 2158, 2238, 2398, 2414, 2446, 2462, 2498, 2514, 2554, 2570, 6880, 6912, 7028, 7044, 7076, 7092, 7124, 7140, 7172, 7188, 9894, 9926 },
        new int[] { 1347, 1403, 1508, 1524, 1556, 1572, 1607, 1623, 1654, 1662, 4283, 4299, 4363, 4371, 4387, 4395, 4411, 4415, 4452, 4457, 4473, 4481, 6161, 6189 },
        new int[] {  },
    };
}
