using Colossal.Localization;
using CS2Mods.Shared;
using CS2Mods.Shared.Discovery;
using CS2Mods.Shared.Infrastructure;
using Game.Net;
using Game.Prefabs;
using Game.SceneFlow;
using System;
using System.Collections.Generic;
using System.Linq;

namespace BridgeBuilder.Bridges;

/// <summary>What a deck carries. Ordered so the dropdown groups sensibly.</summary>
internal enum DeckKind
{
    /// <summary>A road generated by Road Builder, still owned by it.</summary>
    RoadBuilder,

    /// <summary>Any other road: the game's own, a pack's, or one this mod exported earlier.</summary>
    Road,

    Train,
    Subway,
    Tram,
}

/// <summary>One net that can serve as the upper or lower deck of a bridge.</summary>
internal sealed class Deck
{
    internal Deck(NetGeometryPrefab prefab, DeckKind kind, string displayName, float width, RoadBuilderRoad? road)
    {
        Prefab = prefab;
        Kind = kind;
        DisplayName = displayName;
        Width = width;
        Road = road;
    }

    internal NetGeometryPrefab Prefab { get; }

    internal DeckKind Kind { get; }

    /// <summary>The prefab's own name. Stable, so it is what the setting stores.</summary>
    internal string Id => Prefab.name;

    /// <summary>What the player sees: the in-game asset name where there is one.</summary>
    internal string DisplayName { get; }

    /// <summary>Metres, measured from the sections. 0 when it could not be measured.</summary>
    internal float Width { get; }

    /// <summary>
    /// Set only for Road Builder roads. Carries the things that only exist in the Road Builder
    /// configuration - the authored speed limit, the fingerprint, the thumbnail - and which a plain
    /// registered prefab simply does not have.
    /// </summary>
    internal RoadBuilderRoad? Road { get; }

    internal bool IsRoad => Kind is DeckKind.RoadBuilder or DeckKind.Road;

    /// <summary>
    /// The name this deck contributes to a generated asset name. Never the localized display name:
    /// an asset that renamed itself when the player switched language would stop matching its own
    /// record. For a Road Builder road that is the name registered in Road Builder; for anything else
    /// the prefab identifier, which is already stable English.
    /// </summary>
    internal string AssetName => Road?.Name ?? Prefab.name;
}

/// <summary>
/// Everything that can be picked as a deck: Road Builder roads, the roads already registered -
/// including ones this mod exported earlier - and the train, subway and tram tracks.
///
/// Two things are deliberately not in here. Pedestrian and other non-vehicle nets are left out
/// because a bridge deck that carries nothing is not what the picker is for. And nets with their own
/// zoning behaviour are kept, but only as the upper deck; see the export system for why a lower deck
/// has to be stripped of it.
/// </summary>
internal static class DeckCatalog
{
    private static readonly object Gate = new();
    private static List<Deck> _decks = new();
    private static bool _scanned;

    internal static IReadOnlyList<Deck> Decks
    {
        get { lock (Gate) return _decks; }
    }

    internal static bool Scanned
    {
        get { lock (Gate) return _scanned; }
    }

    internal static Deck? Find(string? id)
    {
        if (string.IsNullOrEmpty(id)) return null;
        lock (Gate)
        {
            return _decks.FirstOrDefault(deck => string.Equals(deck.Id, id, StringComparison.Ordinal));
        }
    }

    /// <summary>
    /// Rebuilds the list from what is registered now, with the Road Builder roads that discovery
    /// already described folded in so their configuration travels with them.
    /// </summary>
    internal static void Rebuild(PrefabSystem prefabSystem, IReadOnlyList<RoadBuilderRoad> roads)
    {
        var byPrefab = new Dictionary<PrefabBase, RoadBuilderRoad>(ReferenceEqualityComparer<PrefabBase>.Instance);
        foreach (var road in roads) byPrefab[road.Prefab] = road;

        var decks = new List<Deck>();
        foreach (var prefab in PrefabCatalog.GetAll(prefabSystem).OfType<NetGeometryPrefab>())
        {
            try
            {
                var deck = Describe(prefab, byPrefab);
                if (deck != null) decks.Add(deck);
            }
            catch (Exception)
            {
                // A prefab that cannot be described is a broken asset, not a usable deck.
            }
        }

        var ordered = decks
            .OrderBy(deck => deck.Kind)
            .ThenBy(deck => deck.DisplayName, StringComparer.OrdinalIgnoreCase)
            .ToList();

        lock (Gate)
        {
            _decks = ordered;
            _scanned = true;
        }

        ModHost.Log.Info(
            "Decks available: "
            + string.Join(", ", ordered.GroupBy(deck => deck.Kind).Select(group => $"{group.Key} x{group.Count()}")));
    }

    private static Deck? Describe(NetGeometryPrefab prefab, IReadOnlyDictionary<PrefabBase, RoadBuilderRoad> roads)
    {
        // A bridge is never a deck. It already carries its own span behaviour, towers and pillars, and
        // draping a second bridge over that produces two structures fighting for the same space. This
        // also keeps a generated bridge out of the list it was generated from, which would otherwise
        // let the output of one run become the input of the next and compound the error every time.
        if (prefab.GetComponent<Bridge>() != null) return null;

        if (prefab is TrackPrefab track)
        {
            var kind = KindOf(track.m_TrackType);
            if (kind == null) return null;
            return new Deck(track, kind.Value, DisplayNameOf(track), NetWidth.Of(track), null);
        }

        if (prefab is not RoadPrefab road) return null;

        if (roads.TryGetValue(road, out var builderRoad))
        {
            return new Deck(
                road,
                DeckKind.RoadBuilder,
                builderRoad.Name,
                builderRoad.Width > 0f ? builderRoad.Width : NetWidth.Of(road),
                builderRoad);
        }

        // A Road Builder road that discovery rejected - no usable name, broken configuration - must
        // not come back through this door as an anonymous road prefab.
        if (IsRoadBuilderPrefab(road)) return null;

        return new Deck(road, DeckKind.Road, DisplayNameOf(road), NetWidth.Of(road), null);
    }

    /// <summary>
    /// Road Builder's prefabs are its own subclass of RoadPrefab. Recognised by assembly rather than
    /// by name so that a road called "RoadBuilder something" is not caught by accident.
    /// </summary>
    private static bool IsRoadBuilderPrefab(PrefabBase prefab)
    {
        var type = prefab.GetType();
        return string.Equals(type.Assembly.GetName().Name, "RoadBuilder", StringComparison.OrdinalIgnoreCase)
            || (type.Namespace?.StartsWith("RoadBuilder.", StringComparison.Ordinal) ?? false);
    }

    /// <summary>
    /// Tracks that carry more than one mode are skipped: they would be placed correctly but the label
    /// would be a lie, and the picker exists so the player knows what they are choosing.
    /// </summary>
    private static DeckKind? KindOf(TrackTypes type) => type switch
    {
        TrackTypes.Train => DeckKind.Train,
        TrackTypes.Subway => DeckKind.Subway,
        TrackTypes.Tram => DeckKind.Tram,
        _ => null,
    };

    /// <summary>
    /// The prefab's name as the player has seen it in the game, falling back to the identifier. The
    /// game keeps asset names in its own dictionary, so this reads correctly in the active language
    /// without this mod translating hundreds of road names itself.
    /// </summary>
    internal static string DisplayNameOf(PrefabBase prefab)
    {
        try
        {
            LocalizationDictionary? dictionary = GameManager.instance?.localizationManager?.activeDictionary;
            if (dictionary != null
                && dictionary.TryGetValue($"Assets.NAME[{prefab.name}]", out var localized)
                && !string.IsNullOrWhiteSpace(localized))
            {
                return localized;
            }
        }
        catch (Exception)
        {
            // A missing or half-loaded dictionary must not cost the player the whole deck list.
        }

        return prefab.name;
    }
}
