[CmdletBinding()]
param(
    [string]$GameDir,
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot

function Find-GameDirectory {
    param([string]$RequestedPath)

    if ($RequestedPath) {
        $resolved = [IO.Path]::GetFullPath($RequestedPath)
        if (Test-Path -LiteralPath (Join-Path $resolved 'Cities2_Data\Managed\Game.dll')) { return $resolved }
        throw "Game.dll was not found below: $resolved"
    }

    $candidates = [Collections.Generic.List[string]]::new()
    $steam = Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\WOW6432Node\Valve\Steam' -Name InstallPath -ErrorAction SilentlyContinue
    if ($steam) {
        $candidates.Add((Join-Path $steam 'steamapps\common\Cities Skylines II'))
        $libraries = Join-Path $steam 'steamapps\libraryfolders.vdf'
        if (Test-Path -LiteralPath $libraries) {
            foreach ($match in [regex]::Matches([IO.File]::ReadAllText($libraries), '"path"\s+"([^"]+)"')) {
                $libraryPath = $match.Groups[1].Value.Replace('\\', '\')
                $candidates.Add((Join-Path $libraryPath 'steamapps\common\Cities Skylines II'))
            }
        }
    }

    $candidates.Add('D:\Program Files (x86)\Steam\steamapps\common\Cities Skylines II')
    $candidates.Add('C:\Program Files (x86)\Steam\steamapps\common\Cities Skylines II')
    foreach ($candidate in $candidates | Select-Object -Unique) {
        if (Test-Path -LiteralPath (Join-Path $candidate 'Cities2_Data\Managed\Game.dll')) { return $candidate }
    }
    throw 'Cities: Skylines II was not found. Pass -GameDir explicitly.'
}

$GameDir = Find-GameDirectory $GameDir
$managed = Join-Path $GameDir 'Cities2_Data\Managed'
$dotnet = (Get-Command dotnet -ErrorAction Stop).Source
$dotnetRoot = Split-Path -Parent $dotnet
$sdkVersion = (& $dotnet --version).Trim()
$compiler = Join-Path $dotnetRoot "sdk\$sdkVersion\Roslyn\bincore\csc.dll"
$refPack = Get-ChildItem -LiteralPath (Join-Path $dotnetRoot 'packs\NETStandard.Library.Ref') -Directory |
    Sort-Object { [version]$_.Name } -Descending |
    Select-Object -First 1
if (-not $refPack) { throw 'NETStandard.Library.Ref is not installed with the .NET SDK.' }
$frameworkRefs = Join-Path $refPack.FullName 'ref\netstandard2.1'

$output = Join-Path $projectRoot "src\BridgeBuilder\bin\$Configuration"
[IO.Directory]::CreateDirectory($output) | Out-Null

$uiModule = Join-Path $projectRoot 'src\BridgeBuilder\UI\BridgeBuilder.mjs'
$uiHeader = [IO.File]::ReadAllText($uiModule)
[xml]$project = Get-Content -LiteralPath (Join-Path $projectRoot 'src\BridgeBuilder\BridgeBuilder.csproj') -Raw
$releaseVersion = [string]$project.Project.PropertyGroup.Version
if ($releaseVersion -notmatch '^\d+\.\d+\.\d+$') {
    throw "Expected a three-part release Version in BridgeBuilder.csproj: $releaseVersion"
}
$uiVersion = [regex]::Match($uiHeader, '(?m)^\s*\*\s*Version\s*:\s*(\S+)').Groups[1].Value
if ($uiVersion -ne $releaseVersion) {
    throw "UI version '$uiVersion' does not match project version '$releaseVersion'."
}
# This script invokes csc directly, so SDK GenerateAssemblyInfo does not run.
# Keep csproj as the version authority and generate equivalent compiler input.
$intermediate = Join-Path $projectRoot "src\BridgeBuilder\obj\$Configuration\DirectBuild"
[IO.Directory]::CreateDirectory($intermediate) | Out-Null
$assemblyInfo = Join-Path $intermediate 'BridgeBuilder.AssemblyInfo.cs'
[IO.File]::WriteAllText($assemblyInfo, @"
// Generated by tools/Build.ps1 from BridgeBuilder.csproj. Do not edit.
[assembly: System.Reflection.AssemblyVersion("$releaseVersion.0")]
[assembly: System.Reflection.AssemblyFileVersion("$releaseVersion.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("$releaseVersion")]
"@, [Text.UTF8Encoding]::new($false))
foreach ($requiredHeaderLine in @(
    'Cities:\s*Skylines II UI Module',
    '(?m)^\s*\*\s*Id\s*:',
    '(?m)^\s*\*\s*Author\s*:',
    '(?m)^\s*\*\s*Version\s*:',
    '(?m)^\s*\*\s*Dependencies\s*:'
)) {
    if ($uiHeader -notmatch $requiredHeaderLine) {
        throw "BridgeBuilder.mjs is missing required UI module metadata: $requiredHeaderLine"
    }
}

$references = [Collections.Generic.List[string]]::new()
Get-ChildItem -LiteralPath $frameworkRefs -Filter '*.dll' | ForEach-Object {
    $references.Add('/reference:' + $_.FullName)
}
foreach ($assembly in @(
    'Game.dll',
    'Colossal.Core.dll',
    'Colossal.IO.AssetDatabase.dll',
    'Colossal.Localization.dll',
    'Colossal.Logging.dll',
    'Colossal.Mathematics.dll',
    'Unity.Collections.dll',
    'Colossal.AssetPipeline.dll',
    'Colossal.UI.dll',
    'Colossal.UI.Binding.dll',
    'UnityEngine.CoreModule.dll',
    'UnityEngine.ImageConversionModule.dll',
    'UnityEngine.PhysicsModule.dll',
    'Unity.RenderPipelines.Core.Runtime.dll',
    'Unity.RenderPipelines.HighDefinition.Runtime.dll',
    'Unity.Entities.dll',
    'Unity.Mathematics.dll'
)) {
    $path = Join-Path $managed $assembly
    if (-not (Test-Path -LiteralPath $path)) { throw "Required game assembly is missing: $path" }
    $references.Add('/reference:' + $path)
}

$sharedRoot = Join-Path (Split-Path -Parent $projectRoot) 'CS2ModShared\src'
if (-not (Test-Path -LiteralPath $sharedRoot)) {
    throw "The shared sources are missing: $sharedRoot. Clone CS2ModShared next to this repository."
}
$sources = @(
    (Join-Path $projectRoot 'src\BridgeBuilder'),
    $sharedRoot
) | ForEach-Object { Get-ChildItem -LiteralPath $_ -Recurse -Filter '*.cs' } |
    Where-Object { $_.FullName -notmatch '[\\/](bin|obj)[\\/]' } |
    Select-Object -ExpandProperty FullName
$sources = @($sources) + $assemblyInfo
$arguments = @(
    $compiler,
    '/nologo',
    '/target:library',
    '/deterministic+',
    '/codepage:65001',
    '/optimize+',
    '/debug:portable',
    '/nullable:enable',
    '/langversion:latest',
    ('/out:' + (Join-Path $output 'BridgeBuilder.dll'))
) + $references + $sources

& $dotnet @arguments
if ($LASTEXITCODE -ne 0) { throw "Compilation failed with exit code $LASTEXITCODE" }
Copy-Item -LiteralPath $uiModule -Destination $output -Force
Copy-Item -LiteralPath (Join-Path $projectRoot 'src\BridgeBuilder\UI\BridgeBuilder.css') -Destination $output -Force
Copy-Item -LiteralPath (Join-Path $projectRoot 'assets\BridgeBuilder.svg') -Destination $output -Force
Copy-Item -LiteralPath (Join-Path $projectRoot 'assets\BridgeBuilderToolbar.svg') -Destination $output -Force
foreach ($fieldIcon in @('BridgeBuilderPack.svg', 'BridgeBuilderSearch.svg', 'BridgeBuilderFilter.svg', 'BridgeBuilderArrowDown.svg')) {
    Copy-Item -LiteralPath (Join-Path $projectRoot "assets\$fieldIcon") -Destination $output -Force
}
Write-Host "Built: $(Join-Path $output 'BridgeBuilder.dll')"
